# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CareBare < Formula
  desc "Enforce skill-loading requirements for AI coding agents"
  homepage "https://github.com/Blue-Bear-Security/care-bare"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.1.0/care-bare_0.1.0_darwin_amd64.tar.gz"
      sha256 "499fb65576f8fe4cbd2f4d5a188490083dde9af7b7ef7a20f304eaba37caec0f"

      define_method(:install) do
        bin.install "care-bare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.1.0/care-bare_0.1.0_darwin_arm64.tar.gz"
      sha256 "2b94ef946b9c81b34b604b5e0f76ee6f173135a02000e25abe5be4614ce3b15e"

      define_method(:install) do
        bin.install "care-bare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.1.0/care-bare_0.1.0_linux_amd64.tar.gz"
      sha256 "edf1ffd786984d869d0eeb94b07fbb8a972c51540bfeba2be2e3e2c61f8242c5"
      define_method(:install) do
        bin.install "care-bare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blue-Bear-Security/care-bare/releases/download/v0.1.0/care-bare_0.1.0_linux_arm64.tar.gz"
      sha256 "117c070e96c38e9bf4dd119b83020568100fd2492f55de88aa22493bb36df9b8"
      define_method(:install) do
        bin.install "care-bare"
      end
    end
  end

  test do
    system "#{bin}/care-bare", "version"
  end
end
